"""Shared routing vocabulary for technical and business classifiers."""

COMMON_DOCUMENTARY_HINTS = (
    "manual",
    "pdf",
    "documentacion",
    "documento",
    "normativa",
    "normativo",
    "norma",
    "reglamento",
    "apartado",
    "seccion",
    "capitulo",
    "pagina",
    "pag",
    "segun el manual",
    "segun el documento",
    "segun el pdf",
)

BUSINESS_LICITACIONES_HINTS = (
    "licitacion",
    "licitaciones",
    "oferta",
    "ofertas",
    "adjudicacion",
    "adjudicada",
    "adjudicado",
    "adjudicadas",
    "adjudicados",
    "fecha de adjudicacion",
    "fecha de presentacion",
    "fecha de apertura",
)

BUSINESS_PRODUCCION_HINTS = (
    "produccion",
    "control de produccion",
    "control de obras",
    "cartera",
    "responsable",
    "cuatrimestre",
    "rentabilidad",
    "codigo obra",
    "codigo de obra",
)

BUSINESS_COMMON_HINTS = (
    "importe contratado",
    "cliente",
    "estado",
    "comentarios",
    "numero proyecto",
    "numero oferta",
    "tipo obra",
    "en curso",
    "recientes",
    "mas recientes",
    "vinculadas",
    "vinculados",
    "relacionadas",
    "relacionados",
    "top",
    "ranking",
)

STRONG_BUSINESS_ROUTE_HINTS = BUSINESS_LICITACIONES_HINTS + BUSINESS_PRODUCCION_HINTS + (
    "cierre",
    "produccion estimada",
    "produccion marzo",
    "produccion abril",
    "pipeline",
    "backlog",
    "estudio",
    "estudios",
    "plan ",
    "importe medio",
    "importe promedio",
    "importe adjudicado",
    "probabilidad de adjudicacion",
    "situacion oferta",
    "periodo de ejecucion",
    "tipologia de obra",
)

OPS_SPECIALIZED_DOCUMENTARY_HINTS = (
    "estudio de viabilidad",
    "viabilidad ops",
    "estudio de malaga",
    "estudio malaga",
    "estudio tecnico economico",
    "estudio tecnico-economico",
    "guia eopsa",
    "guia ops completa",
    "guia completa de eopsa",
    "guia para una licitacion ops completa y exitosa",
    "lista de verificacion",
    "demanda energetica",
    "solucion recomendada",
    "muelle objetivo",
    "buques objetivo",
    "potencia instalada necesaria",
    "anteproyecto",
    "anteproyecto ops",
    "infraestructura electrica",
    "memoria de infraestructura",
    "puerto de malaga",
    "terminal de cruceros",
    "puerto de bilbao",
    "santurtzi",
    "modulo ops",
    "subestacion de conversion",
    "sistema de gestion de cables",
    "comunicacion de interes",
    "conformidad de estado miembro",
    "subvencion afif",
    "ayudas afif",
    "cef-t",
    "funding tender opportunities",
)
